// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Blocks() {
  return window['go']['main']['App']['Blocks']();
}

export function ConnectNode(arg1, arg2) {
  return window['go']['main']['App']['ConnectNode'](arg1, arg2);
}

export function CreateWallet() {
  return window['go']['main']['App']['CreateWallet']();
}

export function Dashboard() {
  return window['go']['main']['App']['Dashboard']();
}

export function ExecuteCLI(arg1) {
  return window['go']['main']['App']['ExecuteCLI'](arg1);
}

export function MinePending(arg1) {
  return window['go']['main']['App']['MinePending'](arg1);
}

export function MultiSigOutputs() {
  return window['go']['main']['App']['MultiSigOutputs']();
}

export function Nodes() {
  return window['go']['main']['App']['Nodes']();
}

export function PendingTransactions() {
  return window['go']['main']['App']['PendingTransactions']();
}

export function QueueMultiSigTransaction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['QueueMultiSigTransaction'](arg1, arg2, arg3, arg4, arg5);
}

export function QueueP2PKTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueueP2PKTransaction'](arg1, arg2, arg3, arg4);
}

export function QueueSpendMultiSigTransaction(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['QueueSpendMultiSigTransaction'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function QueueTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueueTransaction'](arg1, arg2, arg3, arg4);
}

export function StartNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartNode'](arg1, arg2, arg3);
}

export function StopNode(arg1) {
  return window['go']['main']['App']['StopNode'](arg1);
}

export function Wallets() {
  return window['go']['main']['App']['Wallets']();
}
