// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Blocks() {
  return window['go']['main']['App']['Blocks']();
}

export function CreateWallet() {
  return window['go']['main']['App']['CreateWallet']();
}

export function Dashboard() {
  return window['go']['main']['App']['Dashboard']();
}

export function MinePending(arg1) {
  return window['go']['main']['App']['MinePending'](arg1);
}

export function PendingTransactions() {
  return window['go']['main']['App']['PendingTransactions']();
}

export function QueueTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueueTransaction'](arg1, arg2, arg3, arg4);
}

export function Wallets() {
  return window['go']['main']['App']['Wallets']();
}
