// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function Blocks():Promise<Array<gui.BlockView>>;

export function CreateWallet():Promise<string>;

export function Dashboard():Promise<gui.DashboardData>;

export function MinePending(arg1:string):Promise<string>;

export function PendingTransactions():Promise<Array<string>>;

export function QueueTransaction(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function Wallets():Promise<Array<gui.WalletView>>;
