// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function Blocks():Promise<Array<gui.BlockView>>;

export function ConnectNode(arg1:string,arg2:string):Promise<void>;

export function CreateWallet():Promise<string>;

export function Dashboard():Promise<gui.DashboardData>;

export function ExecuteCLI(arg1:string):Promise<gui.CommandResult>;

export function InitializeNodeBlockchain(arg1:string,arg2:string):Promise<void>;

export function MineNodePending(arg1:string):Promise<string>;

export function MinePending(arg1:string):Promise<string>;

export function MultiSigOutputs():Promise<Array<gui.MultiSigOutputView>>;

export function Nodes():Promise<Array<gui.NodeStatus>>;

export function PendingTransactions():Promise<Array<string>>;

export function QueueMultiSigTransaction(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<string>;

export function QueueP2PKTransaction(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function QueueSpendMultiSigTransaction(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number,arg6:number):Promise<string>;

export function QueueTransaction(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function RunNetworkQuickDemo():Promise<gui.NetworkDemoResult>;

export function StartNode(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopNode(arg1:string):Promise<void>;

export function SubmitNodeTransaction(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function Wallets():Promise<Array<gui.WalletView>>;
